Prepare the 1.2.0 release
wasmerio/wasmer-python pull request #721
Opened 2023-04-20 09:38 UTC by ayys

This PR is to prepare the 1.2.0 release of wasmer-python. Check the changelog committed in this PR for details.

2023-04-20 12:38 UTC, Michael-F-Bryan requested changes
Let's add links to the tickets in the changelog. Other than that, I'm happy to do a release.

2023-04-20 12:38 UTC, Michael-F-Bryan commented on CHANGELOG.md
> +* Added support for Python 3.10 (#680)
Should these link back to the original issues?

2023-04-20 12:38 UTC, Michael-F-Bryan commented on CHANGELOG.md
> +* Fixed typos in the documentation (#639, #681)
Can you add links for these too?

2023-04-21 13:51 UTC, ayys commented
@Michael-F-Bryan I've added links to all the issues I am pointing at. The pre-release CI is still failing though 😞

2023-04-21 14:48 UTC, Michael-F-Bryan approved these changes

2023-05-01 14:18 UTC, merged